version: 2
jobs:
  test_frontend:
    docker:
      - image: circleci/node:8.9.1

    working_directory: ~/repo

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "react-front/package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            cd react-front
            npm install

      - save_cache:
          paths:
            - react-front/node_modules
          key: v1-dependencies-{{ checksum "react-front/package.json" }}

      # run tests!
      - run:
          name: run javascript tests
          command: |
            cd react-front
            npm test

  test_backend:
    docker:
      - image: circleci/python:3.6.3

    working_directory: ~/repo

    steps:
      - checkout

workflows:
  version: 2
  build_and_test:
    jobs:
      - test_frontend
      - test_backend:
          requires:
            - test_frontend
