version: 2
jobs:
  test_frontend:
    docker:
      - image: circleci/node:8.9.1

    working_directory: ~/repo

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "react-front/package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            cd react-front
            npm install

      - save_cache:
          paths:
            - react-front/node_modules
          key: v1-dependencies-{{ checksum "react-front/package.json" }}

      # run tests!
      - run:
          name: run javascript tests
          command: |
            cd react-front
            npm test

  test_backend:
    docker:
      - image: circleci/python:3.6.3

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "python-back/requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            cd python-back
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "python-back/requirements.txt" }}

      # run tests!
      - run:
          name: run tests
          command: |
            cd python-back
            . venv/bin/activate
            pytest --cov-config ../.coveragerc --cov=server .

      - store_artifacts:
          path: test-reports
          destination: test-reports

workflows:
  version: 2
  build_and_test:
    jobs:
      - test_frontend
      - test_backend:
          requires:
            - test_frontend
