version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.9.1

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

  test_frontend:
      # Download and cache dependencies
      docker:
          - image: circleci/node:8.9.1

      working_directory: ~/repo/react-front
      steps:
          - restore_cache:
              keys:
              - v1-dependencies-{{ checksum "package.json" }}
              # fallback to using the latest cache if no exact match is found
              - v1-dependencies-

          - run: npm install

          - save_cache:
              paths:
                - node_modules
              key: v1-dependencies-{{ checksum "package.json" }}

          # run tests!
          - run: npm test

  test_backend:
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "react-front/package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: cd react-front && npm install

      - save_cache:
          paths:
            - react-front/node_modules
          key: v1-dependencies-{{ checksum "react-front/package.json" }}

      # run tests!
      - run: cd react-front && npm test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test_frontend:
          requires:
              - build
