export const USER_JOINED = 'USER_JOINED';
export const USER_GET_UUID = 'USER_GET_UUID';
export const USER_CLAPPED = 'USER_CLAPPED';
export const USER_CLAPPED_SUCCESS = 'USER_CLAPPED_SUCCESS';
export const LISTEN_HUB_DATA = 'LISTEN_HUB_DATA';
export const UPDATE_USERS = 'UPDATE_USERS';
